name: HistSys Frontend Development CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install && npm run-script build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: export HISTSYS_ENV=dev && npm install && npm run-script build

      - name: Setup Dir
        uses: appleboy/ssh-action@master
        with:
          host: dev.hms.yootane.com
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            mkdir -p /hms_front/dev
            cd /hms_front
            rm -rf ./dev
            mkdir -p ./dev
            echo "🙊Remove Old Source Files Success"

      - name: Copy file via scp
        uses: appleboy/scp-action@master
#        env:
##          KEY: ${{ secrets.SSHKEY2 }}
        with:
          host: dev.hms.yootane.com
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist"
          target: "/hms_front/dev/"
