name: Development Build CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build App
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install && npm run build:production
        # or build:development
