name: HistSys Frontend Production CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: export HISTSYS_ENV=prod && npm install && npm run-script build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: npm install && npm run-script build

      - name: Setup Dir
        uses: appleboy/ssh-action@master
        with:
          host: hms.yootane.com
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            mkdir -p /hms_front/prod
            cd /hms_front
            rm -rf ./prod
            mkdir -p ./prod
            echo "🙊Remove Old Source Files Success"

      - name: Copy file via scp
        uses: appleboy/scp-action@master
#        env:
##          KEY: ${{ secrets.SSHKEY2 }}
        with:
          host: hms.yootane.com
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "./dist"
          target: "/hms_front/prod/"

      - name: Upload files to OSS
        uses: taixw2/deploy-aliyun-oss@v1
          with:
            # aliyun config
            region: oss-cn-shenzhen.aliyuncs.com
            access-key-id: LTAI5tNw1iosfvrxbsxDf5zk
            access-key-secret: fdDXe80fbW4xaRHz6kp5DaRsCuMhLI
            bucket: hms-web
            secure: true
            # deploy config
            entry: dist/**/* # glob pattern
            remote-dir: /release/$(git rev-parse --short "$GITHUB_SHA")
            path-rewrite: ^dist/
